
import 'package:my_project/Model/Category.dart';
import 'package:my_project/Model/Subcategory.dart';

const Catrgory_date=const [
  Catrgory(id:'c1',name:'Clothes',image:'images/m1.jpg'),
  Catrgory(id:'c2',name:'Computers',image:'images/m2.jpg'),
  Catrgory(id:'c3',name:'Cars',image:'images/m3.jpg'),
  Catrgory(id:'c4',name:'CellPhone',image:'images/m4.jpg'),
  Catrgory(id:'c5',name:'Home Chattel',image:'images/m5.jpg'),
  //Catrgory(id:'c6',name:'Stationery',image:'images/m6.jpg'),
  Catrgory(id:'c7',name:'Hardware',image:'images/m7.jpg'),
  Catrgory(id:'c8',name:'Other',image:'images/m8.jpg'),
];
const Sub_category_data=const[
Subcategory(
    id:'m1' ,
    categorys: ['c1'],
    title: 'Coat',
    image: 'images/m6.jpg',
    isnew: Case.New,
    detalis: ['The color is blake'
    'High dome',
   'Lined with fur' ,
    'Clear leather'],
    description: ['Available in size XL XXL XXXL',
    'The manufacture company is XO',
    'Perfect fit',
    'It has four pocket whit an interior pocket'],
    price: '10.000&&',
    origin: Country.syp,
    isnews: true,
    isue: false,
    issyp: true,
      ),
    Subcategory(
    id :'m2' ,
categorys: ['c1'],
title: 'Formal dress',
image: 'images/m6.jpg',
isnew: Case.New,
detalis: ['The color is blake',
'Three pieces',
'White Shirt' ,
'Red tie'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has attactive viewers'],
price: '50.000&&',
origin: Country.trk,
isnews: true,
isue: false,
issyp: false
),
Subcategory(
id:'m3' ,
categorys: ['c1'],
title: 'Leather shoes',
image: 'images/m6.jpg',
isnew: Case.use,
detalis: ['The color is blake and brouwn',
'Sizes 40 41 42 43 44 ',
'Attractive view' ,
'Short stalk'],
description: ['Also available in a long leg',
'The manufacture company is XO',
'Perfect fit',
'It has ventilation holes'],
price: '5.000&&',
origin: Country.gmy,
isnews: false,
isue: true,
issyp: false
),
Subcategory(
id:'m4' ,
categorys: ['c1'],
title: 'Back bag',
image: 'images/m6.jpg',
isnew: Case.New,
detalis: ['The color is blue and black',
'Various sizes',
'It has six big pockets' ,
'non-waterproof'],
description: ['Suitable for all ages',
'The manufacture company is flutter',
'Perfect fit',
'It has usb socket'],
price: '13.000&&',
origin: Country.trk,
isnews: true,
isue: false,
issyp: false
),
Subcategory(
id:'m5' ,
categorys: ['c2'],
title: 'lab',
image: '',
isnew: Case.avg,
detalis: ['The color is blake and silver',
'core i7',
'Ram 8 Gb DDR4' ,
'Hard 1 tb '],
description: ['Gbu nvidia 940mx',
'Asus ',
'It has three usb socket and vga socket',
'Weight'],
price: '100.000.000&&',
origin: Country.syp,
isnews: false,
isue: false,
issyp: true
),
Subcategory(
id:'m6' ,
categorys: ['c2'],
title: 'desk',
image: '',
isnew: Case.use,
detalis: ['Hd Screen',
'core i3',
'Ram 4 Gb' ,
'Hard 500Gb'],
description: ['Gbu Amd',
'power 500A',
'the color is Multiple',
'Fully equipped'],
price: '500.000&&',
origin: Country.usd,
isnews: false,
isue: true,
issyp: false
),
Subcategory(
 id:'m7' ,
categorys: ['c2'],
title: 'ipad',
image: '',
isnew: Case.New,
detalis: ['The color is blake and white',
'8 coren',
'ram 2 gb' ,
'samsung'],
description: ['Comfortable for the hand and eyes',
'Hd Screen',
'phone 0993307069 ',
'we have more than one piece'],
price: '25.000&&',
origin: Country.syp,
isnews: true,
isue: false,
issyp: false
),
Subcategory(
id:'m8' ,
categorys: ['c2'],
title: 'machin',
image: '',
isnew: Case.New,
detalis: ['toshba'
'Huge energy',
'Cooling fans' ,
'bears pressure'],
description: ['44444444444444444',
'444444444444444444444',
'444444444444444444',
'44444444444444444444'],
price: '400.000&&',
origin: Country.trk,
isnews: true,
isue: false,
issyp: false
),
Subcategory(
id:'m9' ,
categorys: ['c3'],
title: 'Coat',
image: '',
isnew: Case.use,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.syp,
isnews: false,
isue: true,
issyp: true
),
Subcategory(
id:'m10' ,
categorys: ['c3'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.trk,
isnews: true,
isue: false,
issyp: false
),
Subcategory(
id:'m11' ,
categorys: ['c3'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.gmy,
isnews: true,
isue: false,
issyp: false
),
Subcategory(

id:'m12' ,
categorys: ['c3'],
title: 'Coat',
image: '',
isnew: Case.avg,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.syp,
isnews: false,
isue: false,
issyp: true
),
Subcategory(
id:'m13' ,
categorys: ['c4'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.trk,
isnews: true,
isue: false,
issyp: false
),
Subcategory(
id:'m14' ,
categorys: ['c4'],
title: 'Coat',
image: '',
isnew: Case.use,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.trk,
isnews: false,
isue: true,
issyp: false
),
Subcategory(
id:'m15' ,
categorys: ['c4'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.syp,
isnews: true,
isue: false,
issyp: true
),
Subcategory(
id:'m16' ,
categorys: ['c4'],
title: 'Coat',
image: '',
isnew: Case.use,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.gmy,
isnews: false,
isue: true,
issyp: false
),
Subcategory(
id:'m17' ,
categorys: ['c5'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.syp,
isnews: true,
isue: false,
issyp: true
),
Subcategory(
id:'m18' ,
categorys: ['c5'],
title: 'Coat',
image: '',
isnew: Case.use,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.trk,
isnews: false,
isue: true,
issyp: false
),
Subcategory(
id:'m19' ,
categorys: ['c5'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.syp,
isnews: true,
isue: false,
issyp: true
),
Subcategory(
id:'m20' ,
categorys: ['c5'],
title: 'Coat',
image: '',
isnew: Case.use,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.trk,
isnews: false,
isue: true,
issyp: false
),
Subcategory(
id:'m21' ,
categorys: ['c7'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.trk,
isnews: true,
isue: false,
issyp: false
),
Subcategory(
id:'m22' ,
categorys: ['c7'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.gmy,
isnews: true,
isue: false,
issyp: false
),
Subcategory(
id:'m23' ,
categorys: ['c7'],
title: 'Coat',
image: '',
isnew: Case.use,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.trk,
isnews: false,
isue: true,
issyp: false
),
Subcategory(
id:'m24' ,
categorys: ['c7'],
title: 'Coat',
image: '',
isnew: Case.New,
detalis: ['The color is blake',
'High dome',
'Lined with fur' ,
'Clear leather'],
description: ['Available in size XL XXL XXXL',
'The manufacture company is XO',
'Perfect fit',
'It has four pocket whit an interior pocket'],
price: '10.000&&',
origin: Country.syp,
isnews: true,
isue: false,
issyp: true
),
];